# Generated by Django 3.1.6 on 2021-02-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='puesto',
            new_name='title',
        ),
    ]
