# Generated by Django 3.1.6 on 2021-02-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210207_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educacion',
        ),
    ]
